import { Client } from '../models/Client';
import { ReminderSetting } from '../models/ReminderSetting';
import { ReminderLog } from '../models/ReminderLog';
import { AppSetting } from '../models/AppSetting';
import { sendEmail } from './emailService';
import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';
dayjs.extend(utc);
import logger from '../utils/logger';

// HTML Template for Contract Expiration
// HTML Template for Contract Expiration
const getExpirationTemplate = (clientName: string, daysRemaining: number, endDate: string, accountManager: string) => {
  const isOverdue = daysRemaining < 0;
  const absdays = Math.abs(daysRemaining);
  const daysLabel = isOverdue ? 'Days Overdue' : 'Days Remaining';
  const daysDisplay = isOverdue ? `${absdays} Days Overdue` : `${absdays} Days Remaining`;
  const badgeColor = isOverdue ? '#DC2626' : '#D97706';
  const badgeBg = isOverdue ? '#FEF2F2' : '#FFFBEB';
  const bodyText = isOverdue
    ? `This is an automated alert that the support contract for <strong style="color: #0F1117;">${clientName}</strong> has <strong style="color: #DC2626;">expired</strong> and is now overdue.`
    : `This is an automated reminder that the support contract for <strong style="color: #0F1117;">${clientName}</strong> is approaching its expiration date.`;

  return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contract Expiration Notice</title>
</head>
<body style="background-color: #f4f6f8; margin: 0; padding: 20px; font-family: 'Inter', Arial, sans-serif;">
<div style="font-family: 'Inter', Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #E8ECF4; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.05); background-color: #ffffff;">
  <div style="background-color: #111318; padding: 24px; text-align: center; border-bottom: 4px solid #E8363D;">
    <h2 style="color: #ffffff; margin: 0; font-size: 20px; font-weight: 700; letter-spacing: 1px;">
      DYNAMICS <span style="color: #E8363D;">SQUARE™</span>
    </h2>
    <p style="color: #aaaaaa; margin: 8px 0 0; font-size: 12px; text-transform: uppercase; letter-spacing: 2px;">
      Contract Expiration Notice
    </p>
  </div>
  
  <div style="padding: 32px 24px; background-color: #ffffff;">
    <p style="font-size: 16px; color: #374151; margin-top: 0;">Hello Team,</p>
    
    <p style="font-size: 15px; color: #4B5568; line-height: 1.6;">
      ${bodyText}
    </p>

    <div style="background-color: #F7F8FC; border-left: 4px solid #E8363D; padding: 16px; margin: 24px 0; border-radius: 0 8px 8px 0;">
      <table style="width: 100%; border-collapse: collapse;">
        <tr>
          <td style="padding: 4px 0; color: #6B7280; font-size: 13px; width: 140px; text-transform: uppercase; font-weight: 700; letter-spacing: 0.5px;">Client Name</td>
          <td style="padding: 4px 0; color: #0F1117; font-size: 15px; font-weight: 600;">${clientName}</td>
        </tr>
        <tr>
          <td style="padding: 4px 0; color: #6B7280; font-size: 13px; text-transform: uppercase; font-weight: 700; letter-spacing: 0.5px;">Expiration Date</td>
          <td style="padding: 4px 0; color: #0F1117; font-size: 15px; font-weight: 600;">${endDate}</td>
        </tr>
        <tr>
          <td style="padding: 4px 0; color: #6B7280; font-size: 13px; text-transform: uppercase; font-weight: 700; letter-spacing: 0.5px;">${daysLabel}</td>
          <td style="padding: 4px 0;">
            <span style="display: inline-block; background-color: ${badgeBg}; color: ${badgeColor}; padding: 2px 10px; border-radius: 99px; font-weight: 700; font-size: 14px;">
              ${daysDisplay}
            </span>
          </td>
        </tr>
        ${accountManager ? `
        <tr>
          <td style="padding: 4px 0; color: #6B7280; font-size: 13px; text-transform: uppercase; font-weight: 700; letter-spacing: 0.5px;">Account Manager</td>
          <td style="padding: 4px 0; color: #0F1117; font-size: 15px;">${accountManager}</td>
        </tr>
        ` : ''}
      </table>
    </div>

    <p style="font-size: 14px; color: #4B5568; line-height: 1.6; margin-bottom: 0;">
      Please take the necessary steps to review the account and initiate the renewal process with the client.
    </p>
  </div>
  
  <div style="background-color: #F9FAFB; border-top: 1px solid #E8ECF4; padding: 16px; text-align: center;">
    <p style="font-size: 12px; color: #9CA3AF; margin: 0;">
      Automatically generated by the Support Report Generator system.<br/>
      Please do not reply to this email.
    </p>
  </div>
</div>
</body>
</html>
`;
};


export async function processReminders(dailyMode: boolean = false) {
  logger.info('Starting automated contract reminder scan...');
  
  try {
    // 1. Get all active configs
    const activeSettings = await ReminderSetting.find({ is_enabled: true }).populate('client_id');

    // Always anchor "today" in UTC for consistent day-diff calculations
    const todayUtc = dayjs.utc().startOf('day');

    // Current UTC time as total minutes for time-window comparison
    const nowUtc = dayjs.utc();
    const currentUtcMinutes = nowUtc.hour() * 60 + nowUtc.minute();
    const currentUtcHHmm = nowUtc.format('HH:mm');

    for (const setting of activeSettings) {
      // send_time is stored in UTC (HH:mm). Compare against current UTC time.
      if (!dailyMode) {
        const sendTimeUtc = setting.send_time || '09:00'; // UTC HH:mm
        const [h, m] = sendTimeUtc.split(':').map(Number);
        const sendTotalMinutes = h * 60 + m;
        const diff = Math.abs(currentUtcMinutes - sendTotalMinutes);
        // Allow a 10-minute window; 1430 guard handles midnight wrap (1440-10)
        if (diff > 9 && diff < 1431) {
          continue;
        }
      }

      const client = setting.client_id as any;
      if (!client || !client.is_active || !client.contract_end_date) {
        continue;
      }

      // Calculate days remaining (UTC date diff — no timezone ambiguity)
      const endDateStr = client.contract_end_date.toISOString().substring(0, 10);
      const endDateUtc = dayjs.utc(endDateStr).startOf('day');
      const daysRemaining = endDateUtc.diff(todayUtc, 'days');

      // Check if this exact daysRemaining matches any of the user's triggers
      const activeTriggers = (setting.reminder_days && setting.reminder_days.length > 0)
        ? setting.reminder_days
        : [30];

      logger.info(`[Reminder] Client: ${client.client_name} | Days remaining: ${daysRemaining} | Triggers: [${activeTriggers}] | Match: ${activeTriggers.includes(daysRemaining)} | UTC time: ${currentUtcHHmm} | Send time (UTC): ${setting.send_time}`);

      if (activeTriggers.includes(daysRemaining)) {
        // Build recipient list
        const toList = setting.recipient_emails || [];
        const ccList = setting.cc_emails || [];
        
        // Ensure unique
        const uniqueTo = [...new Set(toList)];
        const uniqueCc = [...new Set(ccList)].filter(email => !uniqueTo.includes(email));

        if (uniqueTo.length === 0 && uniqueCc.length === 0) {
          logger.warn(`Reminder triggered for ${client.client_name} at ${daysRemaining} days, but no recipients configured.`);
          continue;
        }

        // Before sending, verify we haven't already sent this EXACT trigger today
        // (to prevent double sends if cron runs twice by mistake)
        const alreadySent = await ReminderLog.findOne({
          client_id: client._id,
          days_before: daysRemaining,
          sent_at: { $gte: todayUtc.toDate() } // sent anytime today (UTC)
        });

        if (alreadySent) {
          logger.info(`Already sent ${daysRemaining}-day reminder for ${client.client_name} today. Skipping.`);
          continue;
        }

        // Send Email
        logger.info(`Triggering ${daysRemaining}-day reminder for ${client.client_name}...`);
        
        const isOverdue = daysRemaining < 0;
        const absdays = Math.abs(daysRemaining);
        const subject = isOverdue
          ? `OVERDUE: Contract Expired ${absdays} Days Ago - ${client.client_name}`
          : `Notice: Contract Expiring in ${absdays} Days - ${client.client_name}`;
        const endDateDisplay = dayjs(client.contract_end_date.toISOString().substring(0, 10)).format('MMMM DD, YYYY');
        const html = getExpirationTemplate(
          client.client_name,
          daysRemaining,
          endDateDisplay,
          client.account_manager || 'Not Assigned'
        );

        try {
          const daysLine = isOverdue ? `Days Overdue: ${absdays}` : `Days Remaining: ${absdays}`;
          const text = `Contract Expiration Notice\n\nClient Name: ${client.client_name}\nExpiration Date: ${endDateDisplay}\n${daysLine}\nAccount Manager: ${client.account_manager || 'Not Assigned'}\n\nPlease take the necessary steps to review the account and initiate the renewal process with the client.`;

          await sendEmail({
            to: uniqueTo.length > 0 ? uniqueTo : uniqueCc, // fallback to CC if no TO
            cc: uniqueTo.length > 0 ? uniqueCc : [],
            subject,
            html,
            text
          });

          // Log success
          await ReminderLog.create({
            client_id: client._id,
            days_before: daysRemaining,
            sent_to: [...uniqueTo, ...uniqueCc],
            status: 'sent'
          });

          // Update setting last checked
          setting.last_checked_date = new Date();
          await setting.save();
          
        } catch (err: any) {
          logger.error(`Failed to send reminder for ${client.client_name}:`, err);
          
          await ReminderLog.create({
            client_id: client._id,
            days_before: daysRemaining,
            sent_to: [...uniqueTo, ...uniqueCc],
            status: 'failed',
            error: err.message
          });
        }
      }
    }
    
    logger.info('Finished automated contract reminder scan.');
  } catch (err) {
    logger.error('Error during reminder processing job', err);
  }
}

export async function sendTestReminder(clientId: string, to: string[], cc: string[] = []) {
  const client = await Client.findById(clientId);
  if (!client) throw new Error('Client not found');

  const daysRemaining = client.contract_end_date 
    ? dayjs(client.contract_end_date).startOf('day').diff(dayjs().startOf('day'), 'days')
    : 30;

  const isOverdueTest = daysRemaining < 0;
  const absdaysTest = Math.abs(daysRemaining);
  const subject = isOverdueTest
    ? `[TEST] OVERDUE: Contract Expired ${absdaysTest} Days Ago - ${client.client_name}`
    : `[TEST] Notice: Contract Expiring in ${absdaysTest} Days - ${client.client_name}`;
  const endDateDisplay = client.contract_end_date 
    ? dayjs(client.contract_end_date.toISOString().substring(0, 10)).format('MMMM DD, YYYY') 
    : 'Not Set';

  const html = getExpirationTemplate(
    client.client_name,
    daysRemaining,
    endDateDisplay,
    client.account_manager || 'Not Assigned'
  );

  const daysLineTest = isOverdueTest ? `Days Overdue: ${absdaysTest}` : `Days Remaining: ${absdaysTest}`;
  const text = `Contract Expiration Notice\n\nClient Name: ${client.client_name}\nExpiration Date: ${endDateDisplay}\n${daysLineTest}\nAccount Manager: ${client.account_manager || 'Not Assigned'}\n\nPlease take the necessary steps to review the account and initiate the renewal process with the client.`;

  await sendEmail({
    to,
    cc,
    subject,
    html,
    text
  });
}
