import { Client } from '../models/Client';
import { ReminderSetting } from '../models/ReminderSetting';
import { ReminderLog } from '../models/ReminderLog';
import { AppSetting } from '../models/AppSetting';
import { sendEmail } from './emailService';
import dayjs from 'dayjs';
import logger from '../utils/logger';

// HTML Template for Contract Expiration
// HTML Template for Contract Expiration
const getExpirationTemplate = (clientName: string, daysRemaining: number, endDate: string, accountManager: string) => `
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contract Expiration Notice</title>
</head>
<body style="background-color: #f4f6f8; margin: 0; padding: 20px; font-family: 'Inter', Arial, sans-serif;">
<div style="font-family: 'Inter', Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #E8ECF4; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.05); background-color: #ffffff;">
  <div style="background-color: #111318; padding: 24px; text-align: center; border-bottom: 4px solid #E8363D;">
    <h2 style="color: #ffffff; margin: 0; font-size: 20px; font-weight: 700; letter-spacing: 1px;">
      DYNAMICS <span style="color: #E8363D;">SQUARE™</span>
    </h2>
    <p style="color: #aaaaaa; margin: 8px 0 0; font-size: 12px; text-transform: uppercase; letter-spacing: 2px;">
      Contract Expiration Notice
    </p>
  </div>
  
  <div style="padding: 32px 24px; background-color: #ffffff;">
    <p style="font-size: 16px; color: #374151; margin-top: 0;">Hello Team,</p>
    
    <p style="font-size: 15px; color: #4B5568; line-height: 1.6;">
      This is an automated reminder that the support contract for <strong style="color: #0F1117;">${clientName}</strong> is approaching its expiration date.
    </p>

    <div style="background-color: #F7F8FC; border-left: 4px solid #E8363D; padding: 16px; margin: 24px 0; border-radius: 0 8px 8px 0;">
      <table style="width: 100%; border-collapse: collapse;">
        <tr>
          <td style="padding: 4px 0; color: #6B7280; font-size: 13px; width: 140px; text-transform: uppercase; font-weight: 700; letter-spacing: 0.5px;">Client Name</td>
          <td style="padding: 4px 0; color: #0F1117; font-size: 15px; font-weight: 600;">${clientName}</td>
        </tr>
        <tr>
          <td style="padding: 4px 0; color: #6B7280; font-size: 13px; text-transform: uppercase; font-weight: 700; letter-spacing: 0.5px;">Expiration Date</td>
          <td style="padding: 4px 0; color: #0F1117; font-size: 15px; font-weight: 600;">${endDate}</td>
        </tr>
        <tr>
          <td style="padding: 4px 0; color: #6B7280; font-size: 13px; text-transform: uppercase; font-weight: 700; letter-spacing: 0.5px;">Days Remaining</td>
          <td style="padding: 4px 0;">
            <span style="display: inline-block; background-color: #FEF2F2; color: #DC2626; padding: 2px 10px; border-radius: 99px; font-weight: 700; font-size: 14px;">
              ${daysRemaining} Days
            </span>
          </td>
        </tr>
        ${accountManager ? `
        <tr>
          <td style="padding: 4px 0; color: #6B7280; font-size: 13px; text-transform: uppercase; font-weight: 700; letter-spacing: 0.5px;">Account Manager</td>
          <td style="padding: 4px 0; color: #0F1117; font-size: 15px;">${accountManager}</td>
        </tr>
        ` : ''}
      </table>
    </div>

    <p style="font-size: 14px; color: #4B5568; line-height: 1.6; margin-bottom: 0;">
      Please take the necessary steps to review the account and initiate the renewal process with the client.
    </p>
  </div>
  
  <div style="background-color: #F9FAFB; border-top: 1px solid #E8ECF4; padding: 16px; text-align: center;">
    <p style="font-size: 12px; color: #9CA3AF; margin: 0;">
      Automatically generated by the Support Report Generator system.<br/>
      Please do not reply to this email.
    </p>
  </div>
</div>
</body>
</html>
`;

export async function processReminders() {
  logger.info('Starting automated contract reminder scan...');
  
  try {
    // 1. Get all active configs
    const activeSettings = await ReminderSetting.find({ is_enabled: true }).populate('client_id');
    const todayDate = dayjs().startOf('day');
    const currentHourMinute = dayjs().format('HH:mm');
    
    for (const setting of activeSettings) {
      // Only process this client if their configured time precisely matches the current minute of the system
      const clientSendTime = setting.send_time || '09:00';
      if (clientSendTime !== currentHourMinute) {
        continue; // Skip this client for now, it's not their exact time yet
      }
      const client = setting.client_id as any;
      if (!client || !client.is_active || !client.contract_end_date) {
        continue;
      }

      // Calculate days remaining
      const endDateStr = dayjs(client.contract_end_date).format('YYYY-MM-DD');
      const endDate = dayjs(endDateStr).startOf('day');
      // Number of days until expiration (if negative, it already expired)
      const daysRemaining = endDate.diff(todayDate, 'days');

      // Check if this exact daysRemaining matches any of the user's triggers
      const activeTriggers = (setting.reminder_days && setting.reminder_days.length > 0)
        ? setting.reminder_days
        : [30]; // Absolute fallback

      if (activeTriggers.includes(daysRemaining)) {
        // Build recipient list
        const toList = setting.recipient_emails || [];
        const ccList = setting.cc_emails || [];
        
        // Ensure unique
        const uniqueTo = [...new Set(toList)];
        const uniqueCc = [...new Set(ccList)].filter(email => !uniqueTo.includes(email));

        if (uniqueTo.length === 0 && uniqueCc.length === 0) {
          logger.warn(`Reminder triggered for ${client.client_name} at ${daysRemaining} days, but no recipients configured.`);
          continue;
        }

        // Before sending, verify we haven't already sent this EXACT trigger today
        // (to prevent double sends if cron runs twice by mistake)
        const alreadySent = await ReminderLog.findOne({
          client_id: client._id,
          days_before: daysRemaining,
          sent_at: { $gte: todayDate.toDate() } // sent anytime today
        });

        if (alreadySent) {
          logger.info(`Already sent ${daysRemaining}-day reminder for ${client.client_name} today. Skipping.`);
          continue;
        }

        // Send Email
        logger.info(`Triggering ${daysRemaining}-day reminder for ${client.client_name}...`);
        
        const subject = `Notice: Contract Expiring in ${daysRemaining} Days - ${client.client_name}`;
        const html = getExpirationTemplate(
          client.client_name,
          daysRemaining,
          dayjs(client.contract_end_date).format('MMMM DD, YYYY'),
          client.account_manager || 'Not Assigned'
        );

        try {
          const text = `Contract Expiration Notice\n\nClient Name: ${client.client_name}\nExpiration Date: ${dayjs(client.contract_end_date).format('MMMM DD, YYYY')}\nDays Remaining: ${daysRemaining}\nAccount Manager: ${client.account_manager || 'Not Assigned'}\n\nPlease take the necessary steps to review the account and initiate the renewal process with the client.`;

          await sendEmail({
            to: uniqueTo.length > 0 ? uniqueTo : uniqueCc, // fallback to CC if no TO
            cc: uniqueTo.length > 0 ? uniqueCc : [],
            subject,
            html,
            text
          });

          // Log success
          await ReminderLog.create({
            client_id: client._id,
            days_before: daysRemaining,
            sent_to: [...uniqueTo, ...uniqueCc],
            status: 'sent'
          });

          // Update setting last checked
          setting.last_checked_date = new Date();
          await setting.save();
          
        } catch (err: any) {
          logger.error(`Failed to send reminder for ${client.client_name}:`, err);
          
          await ReminderLog.create({
            client_id: client._id,
            days_before: daysRemaining,
            sent_to: [...uniqueTo, ...uniqueCc],
            status: 'failed',
            error: err.message
          });
        }
      }
    }
    
    logger.info('Finished automated contract reminder scan.');
  } catch (err) {
    logger.error('Error during reminder processing job', err);
  }
}

export async function sendTestReminder(clientId: string, to: string[], cc: string[] = []) {
  const client = await Client.findById(clientId);
  if (!client) throw new Error('Client not found');

  const daysRemaining = client.contract_end_date 
    ? dayjs(client.contract_end_date).startOf('day').diff(dayjs().startOf('day'), 'days')
    : 30;

  const subject = `[TEST] Notice: Contract Expiring in ${daysRemaining} Days - ${client.client_name}`;
  const html = getExpirationTemplate(
    client.client_name,
    daysRemaining,
    client.contract_end_date ? dayjs(client.contract_end_date).format('MMMM DD, YYYY') : 'Not Set',
    client.account_manager || 'Not Assigned'
  );

  const text = `Contract Expiration Notice\n\nClient Name: ${client.client_name}\nExpiration Date: ${client.contract_end_date ? dayjs(client.contract_end_date).format('MMMM DD, YYYY') : 'Not Set'}\nDays Remaining: ${daysRemaining}\nAccount Manager: ${client.account_manager || 'Not Assigned'}\n\nPlease take the necessary steps to review the account and initiate the renewal process with the client.`;

  await sendEmail({
    to,
    cc,
    subject,
    html,
    text
  });
}
